### ISSUE TITLE
Error: transaction underpriced

### ISSUE THREAD

**Issue by Sandeep16ibm** [tkAcharya/kickstart-campaign#2]
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: transaction underpriced
    at /Users/sandeep/Downloads/kickstart-campaign-master/node_modules/web3-provider-engine/subproviders/web3.js:15:44
    at XMLHttpRequest.request.onreadystatechange (/Users/sandeep/Downloads/kickstart-campaign-master/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequest.dispatchEvent (/Users/sandeep/Downloads/kickstart-campaign-master/node_modules/xhr2/lib/xhr2.js:76:20)
    at XMLHttpRequest._setReadyState (/Users/sandeep/Downloads/kickstart-campaign-master/node_modules/xhr2/lib/xhr2.js:422:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/sandeep/Downloads/kickstart-campaign-master/node_modules/xhr2/lib/xhr2.js:616:14)
    at IncomingMessage.<anonymous> (/Users/sandeep/Downloads/kickstart-campaign-master/node_modules/xhr2/lib/xhr2.js:568:23)

**Comment by tkAcharya** [comment]
The "transaction underpriced" error occurs, when you're trying to replace a transaction and the replacing gas price is too low. web3. eth. getTransactionCount() only returns the amount of mined transactions, you can set it up as your wish
